### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by Deviltriss** [sc0ty/subsync#45] opened 2020-01-07 12:30 UTC
First of, I absolutely love your program.

Recently though the program wont open normally, I can only get it to open by running it as administrator, never had to do that before.
That isn't really a problem though, however it also doesn't allow me to drag and drop anymore.
I'm not sure if this is a feature you perhaps removed or if it's supposed to work but doesn't for me anymore.

I am absolutely no programmer, so I apologize if I am missing something perhaps easily fixed, also if this isn't where to post this.

**Comment by sc0ty** [comment] 2020-01-07 17:57
There is new installer for Windows build (introduced in version 0.12). It needs elevated privileges only during installation. Running installed app as regular user should be possible.
Do you have some non-standard security options set in Windows?

Drag & drop should also work seamlessly.

I will look into this.

**Comment by Deviltriss** [comment] 2020-01-07 18:34
I use bitdefender on my device, however this is a recent problem. A few weeks ago, the opening of the app as well as drag and drop worked seamlessly.
I did try to turn bitdefender off to see if it solved either problem, it didnt unfortunately.
Any other security is not by my hand if so, as I haven't changed anything on the computer recently.
Thanks for the help though, I appreciate it.
It's mostly the drag and drop that is missed.

**Comment by sc0ty** [comment] 2020-01-09 20:49
I couldn't reproduce your issues. I've tried also on cleanly installed Windows (on VirtualBox). It's probably something with your setup.

According to [this](https://docs.microsoft.com/pl-pl/archive/blogs/patricka/q-why-doesnt-drag-and-drop-work-when-my-application-is-running-elevated-a-mandatory-integrity-control-and-uipi) drag & drop is disabled for elevated apps. So your two issues are most likely related.

You could try to dump logs from debug version when run as regular user with command:
`subsync-debug.exe --loglevel=DEBUG --logfile=d:\logs.txt`  (set this path to somewhere you have write access).
It may tell us whats wrong unless its blocked before it could start.

Also you could try to delete config and asset files from:
c:\Users\USER\AppData\Roaming\subsync\
c:\ProgramData\subsync\
Maybe you have no rights to read/write some of them?

There is also portable version, could you check if this problem occurs there?

**Comment by sc0ty** [comment] 2020-02-09 09:53
Closing since there is no reply from the user.

**Closed by sc0ty** 2020-02-09 09:53 UTC
Labels: bug
